### ISSUE TITLE
[bug] Hardcoded default branch "master" causes Workflow failure if Default Branch is not called master

### ISSUE THREAD

**Issue by niklas2810** [jimschubert/labeler#1]
**Describe the bug**

Hey there! First of all, I really love this project! However, I've found a bug while setting it up as I ran [this workflow](https://github.com/niklas2810/maven-template/runs/939669270#step:5:7) in one of my projects.

I know I used your project [labeler-action](https://github.com/jimschubert/labeler-action), but I was able to locate the root of the problem is this repository. This is the exception thrown: `time="2020-08-03T08:22:06Z" level=fatal msg="Failed to execute GET https://api.github.com/repos/niklas2810/maven-template/contents/.github?ref=master: 404 No commit found for the ref master []"`

In labeler.go, you simply request the `labeler.yml` file for the branch master. Due to [github/renaming](https://github.com/github/renaming), I now call my default branch `main`. Hardcoding `master` should not be considered good practice, as GitHub plans to make `main` the default name for the primary branch. Source: https://github.com/jimschubert/labeler/blob/f0dc732331d5f848fc0423361355884a21ab9f98/labeler.go#L75
 
**To Reproduce**
1. Create a new GitHub repo with a default branch called `main`.
2. Run the labeler action (or the labeler via terminal).

**Expected behavior/Fix**
The labeler should request the `labeler.yml` file from the _default_ branch, which is not necessarily called `master`. As far as I can see, you can simply leave out the `ref` parameter to retrieve the file. This link (=yours without `ref`) works fine for me: https://api.github.com/repos/niklas2810/maven-template/contents/.github

I have no experience in Go, which is why I don't want to open a pull request myself.

**Screenshots**
Error message and link to workflow linked above.

Thank you so much for this project! I hope that my bug report will help you with fixing this issue 😄

**Comment by jimschubert** [comment]
@niklas2810 thank you for pointing this out. It definitely makes most sense to let the API fall back to the repository's default branch rather than hard-coding master!

Fixed via https://github.com/jimschubert/labeler/commit/cafcbc52a11a4261422d64e9ec31f71c3ab26a3a and I'll work to get it into the action.

**Comment by jimschubert** [comment]
@niklas2810 I've done some testing and pushed consumed this in the action as well. I've also added support for `pull_request_target` events, which are new and allow labeling from forked repositories.
